In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as pyplot
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")

In [2]:
data=pd.read_csv("./MLBH.csv")
data.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
0,Abbotsford,49 Lithgow St,3,h,1490000.0,S,Jellis,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
1,Abbotsford,59A Turner St,3,h,1220000.0,S,Marshall,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
2,Abbotsford,119B Yarra St,3,h,1420000.0,S,Nelson,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
3,Aberfeldie,68 Vida St,3,h,1515000.0,S,Barry,1/04/2017,3040,Western Metropolitan,1543,7.5,Moonee Valley City Council
4,Airport West,92 Clydesdale Rd,2,h,670000.0,S,Nelson,1/04/2017,3042,Western Metropolitan,3464,10.4,Moonee Valley City Council

In [3]:
data.shape

(63023, 13)

In [4]:
data.isnull().sum()

Suburb               0
Address              0
Rooms                0
Type                 0
Price            14590
Method               0
SellerG              0
Date                 0
Postcode             0
Regionname           0
Propertycount        0
Distance             0
CouncilArea          0
dtype: int64

In [5]:
data["Suburb"].unique()

array(['Abbotsford', 'Aberfeldie', 'Airport West', 'Albanvale',
       'Albert Park', 'Albion', 'Alphington', 'Altona', 'Altona Meadows',
       'Altona North', 'Armadale', 'Ascot Vale', 'Ashburton', 'Ashwood',
       'Aspendale', 'Aspendale Gardens', 'Attwood', 'Avondale Heights',
       'Balwyn', 'Balwyn North', 'Bayswater North', 'Beaumaris',
       'Bellfield', 'Bentleigh', 'Bentleigh East', 'Black Rock',
       'Blackburn', 'Blackburn North', 'Blackburn South', 'Bonbeach',
       'Boronia', 'Box Hill', 'Braybrook', 'Brighton', 'Brighton East',
       'Broadmeadows', 'Brunswick', 'Brunswick East', 'Brunswick West',
       'Bulleen', 'Bundoora', 'Burwood', 'Burwood East', 'Camberwell',
       'Canterbury', 'Carlton', 'Carlton North', 'Carnegie',
       'Caroline Springs', 'Carrum', 'Carrum Downs', 'Caulfield East',
       'Caulfield North', 'Caulfield South', 'Chadstone', 'Chelsea',
       'Cheltenham', 'Chintin', 'Clayton', 'Clayton South',
       'Clifton Hill', 'Coburg', 'Coburg North', 'Collingwood',
       'Craigieburn', 'Cranbourne', 'Cranbourne North', 'Croydon',
       'Dallas', 'Dandenong', 'Dandenong North', 'Darley', 'Deepdene',
       'Deer Park', 'Delahey', 'Diamond Creek', 'Dingley Village',
       'Doncaster', 'Doncaster East', 'Donvale', 'Eaglemont',
       'East Melbourne', 'Edithvale', 'Elsternwick', 'Eltham',
       'Eltham North', 'Elwood', 'Endeavour Hills', 'Epping', 'Essendon',
       'Essendon North', 'Essendon West', 'Fairfield', 'Fawkner',
       'Ferntree Gully', 'Fitzroy', 'Fitzroy North', 'Footscray',
       'Forest Hill', 'Frankston', 'Frankston North', 'Frankston South',
       'Gladstone Park', 'Glen Iris', 'Glen Waverley', 'Glenroy',
       'Gowanbrae', 'Greensborough', 'Greenvale', 'Hadfield', 'Hampton',
       'Hawthorn', 'Heathmont', 'Heidelberg', 'Heidelberg Heights',
       'Heidelberg West', 'Highett', 'Hillside', 'Hoppers Crossing',
       'Hughesdale', 'Huntingdale', 'Ivanhoe', 'Ivanhoe East', 'Jacana',
       'Keilor Downs', 'Keilor East', 'Kensington', 'Kew', 'Kew East',
       'Keysborough', 'Kingsville', 'Knoxfield', 'Kurunjang', 'Lalor',
       'Lilydale', 'MacLeod', 'Maidstone', 'Malvern', 'Malvern East',
       'Maribyrnong', 'McKinnon', 'Meadow Heights', 'Melbourne', 'Melton',
       'Mentone', 'Mernda', 'Middle Park', 'Mill Park', 'Mitcham',
       'Montmorency', 'Moonee Ponds', 'Moorabbin', 'Mooroolbark',
       'Mordialloc', 'Mount Waverley', 'Mulgrave', 'Murrumbeena',
       'Narre Warren', 'Newport', 'Noble Park', 'North Melbourne',
       'Northcote', 'Nunawading', 'Oak Park', 'Oakleigh',
       'Oakleigh South', 'Ormond', 'Pakenham', 'Parkdale', 'Parkville',
       'Pascoe Vale', 'Patterson Lakes', 'Plenty', 'Point Cook',
       'Port Melbourne', 'Prahran', 'Preston', 'Reservoir', 'Richmond',
       'Riddells Creek', 'Ringwood', 'Ringwood East', 'Ringwood North',
       'Rosanna', 'Rowville', 'Roxburgh Park', 'Sandringham', 'Scoresby',
       'Seaford', 'Seddon', 'South Melbourne', 'South Morang',
       'South Yarra', 'Southbank', 'Spotswood', 'Springvale', 'St Albans',
       'St Kilda', 'Strathmore', 'Strathmore Heights', 'Sunshine',
       'Sunshine North', 'Sunshine West', 'Surrey Hills', 'Sydenham',
       'Taylors Lakes', 'Templestowe', 'Templestowe Lower', 'Thomastown',
       'Thornbury', 'Toorak', 'Truganina', 'Tullamarine', 'Vermont South',
       'Wantirna', 'Wantirna South', 'Warrandyte', 'Werribee',
       'West Footscray', 'West Melbourne', 'Westmeadows', 'Wheelers Hill',
       'Williamstown', 'Windsor', 'Wollert', 'Wyndham Vale', 'Yarraville',
       'Ardeer', 'Bayswater', 'Berwick', 'Briar Hill', 'Brooklyn',
       'Burnside Heights', 'Cairnlea', 'Clarinda', 'Clyde North',
       'Croydon Hills', 'Croydon North', 'Doreen', 'Emerald',
       'Eumemmerring', 'Gisborne', 'Hallam', 'Hampton East',
       'Healesville', 'Keilor Lodge', 'Kings Park', 'Kingsbury',
       'Lower Plenty', 'Lynbrook', 'Melton South', 'Melton West',
       'Mickleham', 'Mont Albert', 'Montrose', 'Oakleigh East',
       'Princes Hill', 'Rockbank', 'Seabrook', 'Seaholme', 'Skye',
       'Springvale South', 'St Helena', 'Sunbury', 'Tarneit',
       'Taylors Hill', 'Tecoma', 'The Basin', 'Vermont', 'Viewbank',
       'Werribee South', 'Williams Landing', 'Caulfield', 'Croydon South',
       'Flemington', 'Gardenvale', 'Hawthorn East', 'Kealba', 'Keilor',
       'Keilor Park', 'Niddrie', 'Burnley', 'Chirnside Park', 'Cremorne',
       'Glen Huntly', 'Hampton Park', 'Manor Lakes', 'North Warrandyte',
       'Plumpton', 'South Kingsville', 'Wallan', 'Warranwood', 'Watsonia',
       'Doveton', 'Ferny Creek', 'Balaclava', 'Campbellfield', 'Coolaroo',
       'Diggers Rest', 'Heatherton', 'Langwarrin', 'Laverton',
       'Wandin North', 'Watsonia North', 'Yallambie', 'Docklands',
       'Wattle Glen', 'Kooyong', 'Notting Hill', 'Williamstown North',
       'Burnside', 'Chelsea Heights', 'Derrimut', 'Kilsyth',
       'New Gisborne', 'Ripponlea', 'Pentland Hills', 'Cranbourne East',
       'Eynesbury', 'Gisborne South', 'Oaklands Junction', 'Sandhurst',
       'Research', 'Travancore', 'Upwey', 'Waterways', 'Yan Yean',
       'Cranbourne West', 'Wonga Park', 'Beaconsfield', 'Botanic Ridge',
       'Gembrook', 'Kilsyth South', 'Woori Yallock', 'Bacchus Marsh',
       'Macleod', 'Panton Hill', 'Lyndhurst', 'Officer', 'Mount Evelyn',
       'Kalkallo', 'Warrandyte South', 'Lysterfield', 'Guys Hill',
       'Hurstbridge', 'Whittlesea', 'Monbulk', 'Silvan', 'Warburton',
       'Cockatoo', 'Kallista', 'Bullengarook', 'Brookfield', 'Bulla',
       'Seville', 'Olinda', 'Avonsleigh', 'Wildwood', 'Castella',
       'Park Orchards', 'Kalorama', 'Belgrave', 'Beaconsfield Upper',
       'Coldstream', 'Hopetoun Park', 'Toolern Vale', 'Belgrave South',
       'Don Valley', 'Yarra Glen', 'Mount Dandenong', 'Menzies Creek',
       'Cranbourne South', 'Warneet', 'croydon', 'Belgrave Heights',
       'Yarrambat', 'viewbank', 'Maddingley', 'Yarra Junction',
       'Lysterfield South'], dtype=object)

In [6]:
data["Address"].unique()

array(['49 Lithgow St', '59A Turner St', '119B Yarra St', ...,
       '9 Parker Ct', '5 Parkinson Wy', '1 Diadem Wy'], dtype=object)

In [7]:
data["SellerG"].unique()

array(['Jellis', 'Marshall', 'Nelson', 'Barry', 'hockingstuart', 'Cayzer',
       'Douglas', 'Bells', 'Miles', 'Barlow', 'Hunter', 'Ray',
       'Fletchers', 'Walshe', 'Noel', 'Philip', 'Buxton', 'Hodges',
       'Woodards', 'Point', 'Stockdale', 'Purplebricks', 'Biggin',
       'Village', 'Boran', 'Jas', 'Kay', 'Prof', 'YPA', 'Rombotis',
       'Brad', 'J', 'RT', 'Garvey', 'Prowse', 'Domain', 'Sweeney',
       'Donovan', 'Gary', "O'Brien", 'LJ', 'Darras', 'C21', 'Peter',
       'Del', 'Jason', 'Bombay', 'iSell', 'Carter', 'McLennan',
       'buyMyplace', 'Raine', 'Mason', 'Lindellas', 'Parkes', 'Caine',
       'hockingstuart/hockingstuart', 'Morrison', 'Chisholm', 'Whiting',
       'Harcourts', 'Love', 'Frank', 'Rendina', 'Win', 'Schroeder',
       'Collins', 'McGrath', 'Eview', 'Aquire', 'Wilson', 'LLC', 'Roger',
       'Darren', 'Buckingham', 'Nick', 'Prof.', 'Greg', 'Haughton',
       'Edward', 'Iconek', "Sotheby's", "Abercromby's", 'Obrien',
       'Grantham', 'Hoskins', 'Benchmark', 'Thomson', 'Alexkarbon',
       'Matthew', 'RW', 'RE', 'U', 'MICM', 'Compton', 'FN', 'Westside',
       'Considine', 'ASL', 'Reliance', 'Langwell', 'Gardiner', 'Triwest',
       'Williams', 'Gunn&Co', 'Moonee', 'McDonald', 'Appleby',
       'Nicholson', 'Bekdon', 'Metro', "Grant's", 'Melbourne', '@Realty',
       'Ham', 'Morleys', 'Burnham', 'LITTLE', 'William', 'PRDNationwide',
       'Max', 'Only', 'Leyton', 'Maitland', 'Lucas', 'Rounds',
       'Millership', 'L', 'iTRAK', 'Emerson', 'People', 'Paul', 'HAR',
       'JRW', 'Pride', 'PNJ', 'Harcourts/Biggin', 'Red', 'Area', 'Skad',
       'Finders', 'Home', 'The', 'Elite', 'Fletchers/Fletchers',
       'Leeburn', 'Benlor', 'Wyndham', 'Upside', 'R&H', 'Tim', 'Besser',
       'Branon', 'Property', 'Savoy', 'Hamilton', "Buxton/O'Brien",
       'Boutique', 'Collings', 'iHomes', 'Dawson', 'David', 'Zed',
       'Follett', 'Exchanged', 'Rexhepi', 'W.B.', 'Scott', 'Munn',
       'Cocoon', 'United', 'GL', 'Ruralco', 'voglwalpole', 'Hall',
       'REMAX', 'hockingstuart/Sweeney', 'Ash', 'Gold', 'Hill', 'Ryder',
       'hockingstuart/Biggin', 'Bayside', 'Janice', 'Harrington', 'R',
       'G&H', 'Charlton', 'Commercial', 'PSP', 'Flannagan', 'Geoff',
       'S&L', 'hockingstuart/Cayzer', 'Leading', 'Real', 'OBrien', 'LJH',
       'Le', 'Nguyen', 'Rodney', 'Unity', 'Steller', 'Jim', 'Ace', 'JMRE',
       'Castran', 'WeSell', 'M.J', 'iProperty', 'Hayeswinckle',
       'Nardella', 'Brace', 'Century', 'Ross', 'Rayner', 'Asset',
       'Allens', 'Zahn', 'Sanctuary', 'Dingle', 'VICPROP', 'Crane', 'One',
       'Kaye', 'Community', 'Meadows', 'Just', 'McNaughton', 'Cooper',
       'Black', 'North', 'Naison', 'Reach', 'Homes', 'New', "D'Aprano",
       'Len', 'Leased', 'Blue', 'hockingstuart/Village', 'Ascend', 'Ken',
       'Buxton/Buxton', 'Daniel', 'Inner', 'Maddison', 'Peake',
       "Tiernan's", 'Re', 'Professionals', 'Holland', 'Avion', 'Reed',
       'hockingstuart/Barry', 'K.R.Peters', 'Christopher', 'Joseph',
       'Belmar', 'Pagan', 'Galldon', 'Beller', 'Dixon', 'Abley',
       'Chambers', 'Marvelli', 'Kennedy', 'Harrison', 'Trimson', 'Gross',
       'Parkinson', 'Johnston', 'hockingstuart/Harcourts', 'Bowman',
       'Sell', 'Charter', 'MJ', 'Hodges/Hodges', 'Buxton/Marshall', 'A',
       'Collin', 'Watermark', 'Matrix', 'Calder', 'Thomas', 'Shape',
       'Spencer', 'Space', 'McGrath/Langwell', 'Burns', 'Weda', 'JK',
       'Mandy', 'Airport', 'Foxtons', 'Buxton/Advantage', 'Nexus',
       'First', 'Bell', 'Arbee', 'Fletchers/Jellis', 'Alex', 'C',
       'Create', 'Weston', 'TTS', 'Assisi', 'McEwing', 'Raine&Horne',
       'Shine', 'Market', 'Coad', 'Ausin', 'Tanner', 'Ristic', 'Bullen',
       'WHITEFOX', 'PRD', 'Landfield', 'Full', 'MSM', 'Anderson', 'Kelly',
       'VICProp', 'Hooper', 'JY', 'Upper', 'Xynergy', 'VicHomes', 'TRUE',
       'Vicprop', 'UFirst', 'Enrich', 'Sweeney/Advantage', 'Justin',
       'Hodges/Buxton', 'Nicholls', 'hockingstuart/Advantage', 'Open',
       'Leaders', 'Sterling', 'CarlinSmith', 'Mega', 'Sprint',
       'McGrath/Noel', 'Wood', 'Fletchers/One', 'Quinta', 'Flanagan',
       'Jacobs', 'Walsh', 'Woodards/hockingstuart', 'Mitchell',
       'hockingstuart/Buxton', 'P', 'Silver', 'Surreal', 'Judith', 'MIG',
       'hockingstuart/ASL', 'Kontek', 'Harcourts/Harcourts', 'Keatings',
       'Smart', "O'Donoghues", 'Changing', 'Owen', 'Australian',
       'CASTRAN', 'Peninsula', 'Gr8', 'Outlook', 'Davita', 'Lynda',
       'Lazogas', 'Little', 'Town', 'Conley', 'hockingstuart/HAR',
       'Propertyau', 'Batty', 'Sutherland', 'Redina', 'Allan', 'Hume',
       'Knight', 'Blackbird', 'Oriental', 'Better', 'Royston', 'Haven',
       'Platinum', 'Revolve', 'VicBrokers', 'Richardson',
       'Harcourts/Barry', 'Harcourts/LJ', 'Pellegrino', 'Landmark',
       'Doyen', 'Coventry', 'Evolve', 'Clairmont', 'iOne',
       'hockingstuart/Kerr', 'Jupiter', 'Rosin', 'McGrath/Buxton',
       'hockingstuart/Marshall', 'McGrath/First', 'Victory', 'Aumeca',
       'Mindacom', 'Karen', 'AIME', 'Luxe', 'Fletchers/J', 'Meallin',
       'Malvern', 'Mark', 'Bradly', 'Sandhurst', 'Buxton/Find',
       'Christou', 'Craig', 'Sahara', 'We', 'Jamie', 'Sweeney/Burnham',
       'Eric', 'H', 'Regal', 'Luxton', 'Steveway', 'SheSELLS',
       'hockingstuart/Purplebricks', 'Impact', 'Realty', 'Aussie',
       'Patterson', 'SN', 'Waterfront', 'Methven', 'hockingstuart/Jellis',
       'Woodards/Peter', 'Buxton/hockingstuart', 'Kerr', 'Nicholas',
       'Conquest', 'Park', 'Auv', 'For', 'Weast', 'Pavilion', 'Integrity',
       "Private/Tiernan's", 'Harcourts/YPA', 'T', 'Prime', 'Free',
       'Veitch', 'John', 'Joe', 'Bustin', 'Vic', 'Direct', 'Bayview',
       'Leader', 'Oak', 'Can', 'Gellibrand', 'White', 'Jeffrey', 'Icon',
       'Buxton/Hodges', 'Living'], dtype=object)

In [8]:
data["Regionname"].unique()

array(['Northern Metropolitan', 'Western Metropolitan',
       'Southern Metropolitan', 'South-Eastern Metropolitan',
       'Eastern Metropolitan', 'Northern Victoria', 'Western Victoria',
       'Eastern Victoria'], dtype=object)

In [9]:
data["CouncilArea"].unique()

array(['Yarra City Council', 'Moonee Valley City Council',
       'Brimbank City Council', 'Port Phillip City Council',
       'Darebin City Council', 'Hobsons Bay City Council',
       'Stonnington City Council', 'Boroondara City Council',
       'Monash City Council', 'Kingston City Council',
       'Hume City Council', 'Maroondah City Council',
       'Bayside City Council', 'Banyule City Council',
       'Glen Eira City Council', 'Whitehorse City Council',
       'Knox City Council', 'Maribyrnong City Council',
       'Moreland City Council', 'Manningham City Council',
       'Melbourne City Council', 'Melton City Council',
       'Frankston City Council', 'Macedon Ranges Shire Council',
       'Casey City Council', 'Greater Dandenong City Council',
       'Moorabool Shire Council', 'Nillumbik Shire Council',
       'Whittlesea City Council', 'Wyndham City Council',
       'Yarra Ranges Shire Council', 'Cardinia Shire Council',
       'Mitchell Shire Council', 'Murrindindi Shire Council'],
      dtype=object)

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63023 entries, 0 to 63022
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         63023 non-null  object
 1   Address        63023 non-null  object
 2   Rooms          63023 non-null  int64
 3   Type           63023 non-null  object
 4   Price          48433 non-null  float64
 5   Method         63023 non-null  object
 6   SellerG        63023 non-null  object
 7   Date           63023 non-null  object
 8   Postcode       63023 non-null  int64
 9   Regionname     63023 non-null  object
 10  Propertycount  63023 non-null  int64
 11  Distance       63023 non-null  float64
 12  CouncilArea    63023 non-null  object
dtypes: float64(2), int64(3), object(8)
memory usage: 6.3+ MB

In [11]:
data["Type"].value_counts()

Type
h    45053
u    11655
t     6315
Name: count, dtype: int64

In [12]:
data["Rooms"].unique()

array([ 3,  2,  6,  4,  1,  5,  7,  8, 11, 10, 12,  9, 31, 16],
      dtype=int64)

In [13]:
data["Price"].fillna(data["Price"].median(),inplace=True)

In [14]:
data.isnull().sum()

Suburb           0
Address          0
Rooms            0
Type             0
Price            0
Method           0
SellerG          0
Date             0
Postcode         0
Regionname       0
Propertycount    0
Distance         0
CouncilArea      0
dtype: int64

In [15]:
data.head(3)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
0,Abbotsford,49 Lithgow St,3,h,1490000.0,S,Jellis,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
1,Abbotsford,59A Turner St,3,h,1220000.0,S,Marshall,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
2,Abbotsford,119B Yarra St,3,h,1420000.0,S,Nelson,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council

In [16]:
data["Streetno"] = data["Address"].apply(lambda x:x.split(" ")[0])
data["Streetname"] = data["Address"].apply(lambda x:x.split(" ")[1])

In [17]:
data["Streetname"]

0           Lithgow
1            Turner
2             Yarra
3              Vida
4        Clydesdale
            ...
63018          Carr
63019        Parker
63020     Parkinson
63021       Travers
63022        Diadem
Name: Streetname, Length: 63023, dtype: object

In [18]:
data.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea,Streetno,Streetname
0,Abbotsford,49 Lithgow St,3,h,1490000.0,S,Jellis,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council,49,Lithgow
1,Abbotsford,59A Turner St,3,h,1220000.0,S,Marshall,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council,59A,Turner
2,Abbotsford,119B Yarra St,3,h,1420000.0,S,Nelson,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council,119B,Yarra
3,Aberfeldie,68 Vida St,3,h,1515000.0,S,Barry,1/04/2017,3040,Western Metropolitan,1543,7.5,Moonee Valley City Council,68,Vida
4,Airport West,92 Clydesdale Rd,2,h,670000.0,S,Nelson,1/04/2017,3042,Western Metropolitan,3464,10.4,Moonee Valley City Council,92,Clydesdale

In [19]:
data.drop(["Address","Streetno"],axis=1,inplace=True)

In [20]:
data.head(3)

,Suburb,Rooms,Type,Price,Method,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea,Streetname
0,Abbotsford,3,h,1490000.0,S,Jellis,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council,Lithgow
1,Abbotsford,3,h,1220000.0,S,Marshall,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council,Turner
2,Abbotsford,3,h,1420000.0,S,Nelson,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council,Yarra

In [21]:
data["Day"] = data["Date"].str.split("/").str[0]
data["Month"] = data["Date"].str.split("/").str[1]
data["Year"] = data["Date"].str.split("/").str[2]

In [22]:
data.drop("Date",axis=1,inplace=True)

In [23]:
data.head(3)

,Suburb,Rooms,Type,Price,Method,SellerG,Postcode,Regionname,Propertycount,Distance,CouncilArea,Streetname,Day,Month,Year
0,Abbotsford,3,h,1490000.0,S,Jellis,3067,Northern Metropolitan,4019,3.0,Yarra City Council,Lithgow,1,04,2017
1,Abbotsford,3,h,1220000.0,S,Marshall,3067,Northern Metropolitan,4019,3.0,Yarra City Council,Turner,1,04,2017
2,Abbotsford,3,h,1420000.0,S,Nelson,3067,Northern Metropolitan,4019,3.0,Yarra City Council,Yarra,1,04,2017

In [24]:
data["Day"]= data["Day"].astype(int)
data["Month"]= data["Month"].astype(int)
data["Year"]= data["Year"].astype(int)

In [25]:
data["Streetname"].value_counts()

Streetname
The         410
High        269
Victoria    229
Park        224
St          206
           ...
Holbeck       1
Mankina       1
Ickworth      1
Sentinel      1
Diadem        1
Name: count, Length: 10191, dtype: int64

In [26]:
num_features = [feature for feature in data.columns if data[feature].dtype!="O"]
print("Numeric_Features: ",(num_features))
cat_features = [feature for feature in data.columns if data[feature].dtype=="O"]
print("Categorical_Features:",len(cat_features))
discreate_features = [feature for feature in num_features if len(data[feature].unique())<=25]
print("Discreate_Features:",len(discreate_features))
continues_features = [feature for feature in num_features if feature not in discreate_features]
print("Continues_Features:",len(continues_features))

Numeric_Features:  ['Rooms', 'Price', 'Postcode', 'Propertycount', 'Distance', 'Day', 'Month', 'Year']
Categorical_Features: 7
Discreate_Features: 3
Continues_Features: 5

In [27]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data["Suburb"]=le.fit_transform(data["Suburb"])
data["SellerG"]=le.fit_transform(data["SellerG"])
data["CouncilArea"]=le.fit_transform(data["CouncilArea"])
data["Streetname"]=le.fit_transform(data["Streetname"])
data["Regionname"]=le.fit_transform(data["Regionname"])

In [28]:
data["Suburb"]=data["Suburb"].astype(int)
data["SellerG"]=data["SellerG"].astype(int)
data["CouncilArea"]=data["CouncilArea"].astype(int)
data["Regionname"]=data["Regionname"].astype(int)
data["Streetname"]=data["Streetname"].astype(int)

In [29]:
## Indpendent and dependent features
from sklearn.model_selection import train_test_split
X = data.drop(['Price'], axis=1)
y = data['Price']

In [30]:
X.head()

,Suburb,Rooms,Type,Method,SellerG,Postcode,Regionname,Propertycount,Distance,CouncilArea,Streetname,Day,Month,Year
0,0,3,h,S,198,3067,2,4019,3.0,32,5600,1,4,2017
1,0,3,h,S,255,3067,2,4019,3.0,32,9310,1,4,2017
2,0,3,h,S,286,3067,2,4019,3.0,32,10105,1,4,2017
3,1,3,h,S,28,3040,6,1543,7.5,22,9467,1,4,2017
4,2,2,h,S,286,3042,6,3464,10.4,22,1986,1,4,2017

In [31]:
num_features = X.select_dtypes(exclude="object").columns
oh_columns = ["Type","Method"]


from sklearn.preprocessing import OneHotEncoder,LabelEncoder,StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer = StandardScaler()
oh_transformer = OneHotEncoder(drop="first")

preprocessor = ColumnTransformer(
    [
        ("OneHotencoder",oh_transformer,oh_columns),
        ("StandardScaler",numeric_transformer,num_features)
        
        
    ],remainder="passthrough"
)

In [32]:
preprocessor

ColumnTransformer(remainder='passthrough',
                  transformers=[('OneHotencoder', OneHotEncoder(drop='first'),
                                 ['Type', 'Method']),
                                ('StandardScaler', StandardScaler(),
                                 Index(['Suburb', 'Rooms', 'SellerG', 'Postcode', 'Regionname', 'Propertycount',
       'Distance', 'CouncilArea', 'Streetname', 'Day', 'Month', 'Year'],
      dtype='object'))])

In [33]:
X.head()

,Suburb,Rooms,Type,Method,SellerG,Postcode,Regionname,Propertycount,Distance,CouncilArea,Streetname,Day,Month,Year
0,0,3,h,S,198,3067,2,4019,3.0,32,5600,1,4,2017
1,0,3,h,S,255,3067,2,4019,3.0,32,9310,1,4,2017
2,0,3,h,S,286,3067,2,4019,3.0,32,10105,1,4,2017
3,1,3,h,S,28,3040,6,1543,7.5,22,9467,1,4,2017
4,2,2,h,S,286,3042,6,3464,10.4,22,1986,1,4,2017

In [34]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63023 entries, 0 to 63022
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         63023 non-null  int32
 1   Rooms          63023 non-null  int64
 2   Type           63023 non-null  object
 3   Price          63023 non-null  float64
 4   Method         63023 non-null  object
 5   SellerG        63023 non-null  int32
 6   Postcode       63023 non-null  int64
 7   Regionname     63023 non-null  int32
 8   Propertycount  63023 non-null  int64
 9   Distance       63023 non-null  float64
 10  CouncilArea    63023 non-null  int32
 11  Streetname     63023 non-null  int32
 12  Day            63023 non-null  int32
 13  Month          63023 non-null  int32
 14  Year           63023 non-null  int32
dtypes: float64(2), int32(8), int64(3), object(2)
memory usage: 5.3+ MB

In [35]:
X=preprocessor.fit_transform(X)

In [36]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63023 entries, 0 to 63022
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         63023 non-null  int32
 1   Rooms          63023 non-null  int64
 2   Type           63023 non-null  object
 3   Price          63023 non-null  float64
 4   Method         63023 non-null  object
 5   SellerG        63023 non-null  int32
 6   Postcode       63023 non-null  int64
 7   Regionname     63023 non-null  int32
 8   Propertycount  63023 non-null  int64
 9   Distance       63023 non-null  float64
 10  CouncilArea    63023 non-null  int32
 11  Streetname     63023 non-null  int32
 12  Day            63023 non-null  int32
 13  Month          63023 non-null  int32
 14  Year           63023 non-null  int32
dtypes: float64(2), int32(8), int64(3), object(2)
memory usage: 5.3+ MB

In [37]:

pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.206881,-0.467053,-0.673681,-0.813384,-1.275670,1.754437,0.159761,-1.766076,-0.966675,-0.068301
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.204271,-0.467053,-0.673681,-0.813384,-1.275670,1.754437,1.409710,-1.766076,-0.966675,-0.068301
2,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.427880,-0.467053,-0.673681,-0.813384,-1.275670,1.754437,1.677557,-1.766076,-0.966675,-0.068301
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.433123,-0.681976,1.205818,-1.373010,-0.682937,0.774961,1.462606,-1.766076,-0.966675,-0.068301
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.427880,-0.666056,1.205818,-0.938825,-0.300954,0.774961,-1.057845,-1.766076,-0.966675,-0.068301
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63018,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.846245,-0.490933,-0.673681,-0.403384,1.042573,-0.302462,-1.173407,1.767119,-1.289514,1.236895
63019,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.846245,-0.490933,-0.673681,-0.403384,1.042573,-0.302462,0.715668,1.767119,-1.289514,1.236895
63020,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.846245,-0.490933,-0.673681,-0.403384,1.042573,-0.302462,0.718027,1.767119,-1.289514,1.236895
63021,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.433123,-0.411332,-0.673681,0.076230,0.344466,1.558542,1.378377,1.767119,-1.289514,1.236895
63022,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,-1.469189,-0.785458,1.205818,-1.269945,0.647418,1.656489,-0.848285,1.767119,-1.289514,1.236895

In [38]:
## separate dataset into train and test
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=.20,random_state=42)
X_train.shape,X_test.shape

((50418, 22), (12605, 22))

## Model Training And Model Selection¶

In [39]:
import xgboost as xgb

In [40]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from xgboost import XGBRegressor
from sklearn.linear_model import LinearRegression, Ridge,Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [41]:
##Create a Function to Evaluate Model
def evaluate_model(true,predicted):
    mae = mean_absolute_error(true,predicted)
    mse = mean_squared_error(true,predicted)
    rmse = mean_squared_error(true,predicted)
    r2_square = r2_score(true, predicted)
    return mae, rmse, r2_square

In [42]:
## Beginning Model Training
models = {
    "Linear Regression": LinearRegression(),
    "lasso": Lasso(),
    "Ridge": Ridge(),
    "K-Neighbors Regressor": KNeighborsRegressor(),
    "Decision Tree": DecisionTreeRegressor(),
    "Random Forest Regressor": RandomForestRegressor(),
    "Adaboost Regressor":AdaBoostRegressor(),
    "XGBoost Regressor":XGBRegressor(),
    "Grediant boost":GradientBoostingRegressor()
}

for i in range (len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train,y_train)  ## Train model


    y_train_pred = model.predict(X_train)
    y_test_pred= model.predict(X_test)

    # Evaluate Train and Test dataset
    model_train_mae , model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)

    model_test_mae , model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)


    print(list(models.keys())[i])
    
    print('Model performance for Training set')
    print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
    print("- R2 Score: {:.4f}".format(model_train_r2))

    print('----------------------------------')
    
    print('Model performance for Test set')
    print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
    print("- R2 Score: {:.4f}".format(model_test_r2))
    
    print('='*35)
    print('\n')

Linear Regression
Model performance for Training set
- Root Mean Squared Error: 195247534863.3522
- Mean Absolute Error: 293160.2444
- R2 Score: 0.2977
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 191059696878.2847
- Mean Absolute Error: 292512.2556
- R2 Score: 0.2830
===================================


lasso
Model performance for Training set
- Root Mean Squared Error: 195247536147.2032
- Mean Absolute Error: 293159.1698
- R2 Score: 0.2977
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 191059745856.5417
- Mean Absolute Error: 292511.3024
- R2 Score: 0.2830
===================================


Ridge
Model performance for Training set
- Root Mean Squared Error: 195247538031.1238
- Mean Absolute Error: 293157.4945
- R2 Score: 0.2977
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 191059833219.1140
- Mean Absolute Error: 292509.8822
- R2 Score: 0.2830
===================================


K-Neighbors Regressor
Model performance for Training set
- Root Mean Squared Error: 116088149035.2518
- Mean Absolute Error: 204781.1948
- R2 Score: 0.5824
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 170958236907.4291
- Mean Absolute Error: 250710.7639
- R2 Score: 0.3585
===================================


Decision Tree
Model performance for Training set
- Root Mean Squared Error: 90959379.9833
- Mean Absolute Error: 240.7712
- R2 Score: 0.9997
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 245418615832.2435
- Mean Absolute Error: 263603.4830
- R2 Score: 0.0790
===================================


Random Forest Regressor
Model performance for Training set
- Root Mean Squared Error: 19261002108.8995
- Mean Absolute Error: 77183.2101
- R2 Score: 0.9307
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 132619864420.8522
- Mean Absolute Error: 206085.2906
- R2 Score: 0.5023
===================================


Adaboost Regressor
Model performance for Training set
- Root Mean Squared Error: 917280396630.8693
- Mean Absolute Error: 855080.4136
- R2 Score: -2.2995
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 911359066017.1805
- Mean Absolute Error: 852651.4248
- R2 Score: -2.4200
===================================


XGBoost Regressor
Model performance for Training set
- Root Mean Squared Error: 90571988194.9501
- Mean Absolute Error: 181237.4258
- R2 Score: 0.6742
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 127611188553.1194
- Mean Absolute Error: 209512.3303
- R2 Score: 0.5211
===================================


Grediant boost
Model performance for Training set
- Root Mean Squared Error: 143196793605.5352
- Mean Absolute Error: 227107.0931
- R2 Score: 0.4849
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 139841267993.8273
- Mean Absolute Error: 227664.2392
- R2 Score: 0.4752
===================================

In [43]:
#Initialize few parameter for Hyperparamter tuning

rf_params = {"max_depth": [5, 8, 15, None, 10],
             "max_features": [5, 7, "auto", 8],
             "min_samples_split": [2, 8, 15, 20],
             "n_estimators": [100, 200, 500, 1000]}
Xgboost_params = {"max_depth": [5, 8, 12, 20, 30],
                  "n_estimators": [100, 200, 300],
                  "n_jobs":[1,-1,2,-2]}

In [44]:
# Models list for Hyperparameter tuning
randomcv_models = [("RF", RandomForestRegressor(), rf_params),
                   ("Xgboost", XGBRegressor(), Xgboost_params)
                  ]

In [ ]:
##Hyperparameter Tuning
from sklearn.model_selection import RandomizedSearchCV

model_param = {}
for name, model, params in randomcv_models:
    random = RandomizedSearchCV(estimator=model,
                                   param_distributions=params,
                                   n_iter=100,
                                   cv=3,
                                   verbose=2,
                                   n_jobs=-1)
    random.fit(X_train, y_train)
    model_param[name] = random.best_params_

for model_name in model_param:
    print(f"---------------- Best Params for {model_name} -------------------")
    print(model_param[model_name])

Fitting 3 folds for each of 100 candidates, totalling 300 fits

In [ ]:
## Retraining the models with best parameters
models = {
    "Random Forest Regressor": RandomForestRegressor(n_estimators=100, min_samples_split=2, max_features=5, max_depth=None, 
                                                     n_jobs=-1),
    "Xgboost":XGBoostRegressor(n_estimators=60,)
    
}
for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train) # Train model

    # Make predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    model_train_mae , model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)

    model_test_mae , model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)
    
    print(list(models.keys())[i])
    
    print('Model performance for Training set')
    print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
    print("- R2 Score: {:.4f}".format(model_train_r2))

    print('----------------------------------')
    
    print('Model performance for Test set')
    print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
    print("- R2 Score: {:.4f}".format(model_test_r2))
    
    print('='*35)
    print('\n')